name: Rust Build and Push
on:
  push:
    tags: ['v*']

env:
  GCR_HOST: gcr.io
  IMAGE_NAME: axum-template
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_DEV_DEBUG: 0
  CARGO_PROFILE_DEV_STRIP: debuginfo

jobs:
  build_push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Login to GCR
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v4

      - name: Configure Docker Client
        run: gcloud auth configure-docker --quiet

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.GCR_HOST}}/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
